from enum import Enum


class ProposalStatus(str, Enum):
    PROPOSAL_READY = "PROPOSAL_READY"
    NO_PROPOSAL_NEEDED = "NO_PROPOSAL_NEEDED"
    NOT_ELIGIBLE = "NOT_ELIGIBLE"
    NEEDS_MORE_DATA = "NEEDS_MORE_DATA"
    BLOCKED_BY_CONFIDENCE = "BLOCKED_BY_CONFIDENCE"
    BLOCKED_BY_COOLDOWN = "BLOCKED_BY_COOLDOWN"
    UNSUPPORTED_REVIEW_DOMAIN = "UNSUPPORTED_REVIEW_DOMAIN"
    ADAPTIVE_LIMIT_REACHED = "ADAPTIVE_LIMIT_REACHED"
    NEEDS_NEW_EVALUATION = "NEEDS_NEW_EVALUATION"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"


class ProposalLifecycleState(str, Enum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    APPLIED = "APPLIED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    SUPERSEDED = "SUPERSEDED"
    CANCELLED = "CANCELLED"


class ProposalType(str, Enum):
    ENERGY_TARGET_INCREASE = "ENERGY_TARGET_INCREASE"
    HOLD_CURRENT_TARGET = "HOLD_CURRENT_TARGET"


class AdjustmentProposalReasonCode(str, Enum):
    FLAT_WEIGHT_TREND_WITH_HIGH_ADHERENCE = "FLAT_WEIGHT_TREND_WITH_HIGH_ADHERENCE"
    SUFFICIENT_MULTI_WEEK_EVIDENCE = "SUFFICIENT_MULTI_WEEK_EVIDENCE"
    ENERGY_TARGET_REVIEW_RECOMMENDED = "ENERGY_TARGET_REVIEW_RECOMMENDED"
    LOW_WEIGHT_TREND_CONFIDENCE = "LOW_WEIGHT_TREND_CONFIDENCE"
    LOW_EVALUATION_CONFIDENCE = "LOW_EVALUATION_CONFIDENCE"
    COOLDOWN_ACTIVE = "COOLDOWN_ACTIVE"
    ADAPTIVE_LIMIT_REACHED = "ADAPTIVE_LIMIT_REACHED"
    ELIGIBILITY_NOT_VALID = "ELIGIBILITY_NOT_VALID"
    EVALUATION_STALE = "EVALUATION_STALE"
    NEW_EVIDENCE_AVAILABLE = "NEW_EVIDENCE_AVAILABLE"
    UNSUPPORTED_REVIEW_DOMAIN = "UNSUPPORTED_REVIEW_DOMAIN"
    UNSUPPORTED_GOAL = "UNSUPPORTED_GOAL"
    INSUFFICIENT_EVALUATION_WINDOW = "INSUFFICIENT_EVALUATION_WINDOW"
    PROPOSAL_STALE = "PROPOSAL_STALE"


class RiskFlag(str, Enum):
    LOW_WEIGHT_TREND_CONFIDENCE = "LOW_WEIGHT_TREND_CONFIDENCE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    ADAPTIVE_LIMIT_NEAR = "ADAPTIVE_LIMIT_NEAR"
    PROPOSAL_EXPIRED = "PROPOSAL_EXPIRED"
    ELIGIBILITY_CHANGED = "ELIGIBILITY_CHANGED"
    COOLDOWN_ACTIVE = "COOLDOWN_ACTIVE"
    EVALUATION_STALE = "EVALUATION_STALE"
    NEW_EVIDENCE_AVAILABLE = "NEW_EVIDENCE_AVAILABLE"


class ProposalPolicy:
    VERSION = "NUTRITION_ADJUSTMENT_PROPOSAL_V01"
    ENERGY_ADJUSTMENT_POLICY = "NUTRITION_ENERGY_ADJUSTMENT_V01"
    CONFIDENCE_POLICY = "NUTRITION_ADJUSTMENT_CONFIDENCE_V01"
    VALIDITY_POLICY = "NUTRITION_PROPOSAL_VALIDITY_V01"
    FRESHNESS_POLICY = "NUTRITION_EVALUATION_FRESHNESS_V01"

    DEFAULT_ENERGY_ADJUSTMENT_STEP_KCAL: int = 100
    MAX_SINGLE_ENERGY_ADJUSTMENT_KCAL: int = 100
    MAX_CUMULATIVE_ADAPTIVE_ADJUSTMENT_KCAL: int = 400
    PROPOSAL_VALIDITY_HOURS: int = 48
    COOLDOWN_DAYS: int = 7
