from enum import Enum


class SourceType(str, Enum):
    FOOD_COMPOSITION_TABLE = "FOOD_COMPOSITION_TABLE"
    PRODUCT_LABEL = "PRODUCT_LABEL"
    OFFICIAL_REGULATORY_SOURCE = "OFFICIAL_REGULATORY_SOURCE"
    CURATED_INTERNAL = "CURATED_INTERNAL"
    USER_PROVIDED = "USER_PROVIDED"


class FoodEntityType(str, Enum):
    GENERIC_FOOD = "GENERIC_FOOD"
    PREPARED_FOOD = "PREPARED_FOOD"
    PACKAGED_PRODUCT = "PACKAGED_PRODUCT"


class PreparationState(str, Enum):
    RAW = "RAW"
    COOKED = "COOKED"
    BOILED = "BOILED"
    STEAMED = "STEAMED"
    FRIED = "FRIED"
    BAKED = "BAKED"
    ROASTED = "ROASTED"
    DRIED = "DRIED"
    FERMENTED = "FERMENTED"
    PROCESSED = "PROCESSED"
    READY_TO_EAT = "READY_TO_EAT"
    UNKNOWN = "UNKNOWN"


class FoodCategory(str, Enum):
    GRAIN_STAPLE = "GRAIN_STAPLE"
    TUBER = "TUBER"
    LEGUME = "LEGUME"
    VEGETABLE = "VEGETABLE"
    FRUIT = "FRUIT"
    MEAT = "MEAT"
    POULTRY = "POULTRY"
    FISH_SEAFOOD = "FISH_SEAFOOD"
    EGG = "EGG"
    DAIRY = "DAIRY"
    SOY_PRODUCT = "SOY_PRODUCT"
    NUT_SEED = "NUT_SEED"
    FAT_OIL = "FAT_OIL"
    SUGAR_SWEETENER = "SUGAR_SWEETENER"
    BEVERAGE = "BEVERAGE"
    PREPARED_DISH = "PREPARED_DISH"
    SNACK = "SNACK"
    CONDIMENT = "CONDIMENT"
    OTHER = "OTHER"


class BasisType(str, Enum):
    PER_100_G_EDIBLE = "PER_100_G_EDIBLE"
    PER_100_G_AS_SOLD = "PER_100_G_AS_SOLD"
    PER_100_ML = "PER_100_ML"
    PER_SERVING = "PER_SERVING"
    PER_PACKAGE = "PER_PACKAGE"
    CUSTOM = "CUSTOM"


class DataQualityStatus(str, Enum):
    VERIFIED_OFFICIAL = "VERIFIED_OFFICIAL"
    VERIFIED_CURATED = "VERIFIED_CURATED"
    UNVERIFIED = "UNVERIFIED"
    DEPRECATED = "DEPRECATED"


class NutrientCompleteness(str, Enum):
    CORE_COMPLETE = "CORE_COMPLETE"
    PARTIAL = "PARTIAL"
    INSUFFICIENT = "INSUFFICIENT"


class AliasType(str, Enum):
    COMMON_NAME = "COMMON_NAME"
    LOCAL_NAME = "LOCAL_NAME"
    SPELLING_VARIANT = "SPELLING_VARIANT"
    SEARCH_SYNONYM = "SEARCH_SYNONYM"
    BRAND_ALIAS = "BRAND_ALIAS"


class ServingSourceType(str, Enum):
    OFFICIAL_SOURCE = "OFFICIAL_SOURCE"
    MEASURED_CURATED = "MEASURED_CURATED"
    PRODUCT_LABEL = "PRODUCT_LABEL"
    USER_DEFINED = "USER_DEFINED"
    ESTIMATED = "ESTIMATED"


class ServingConfidence(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class ServingDivisibility(str, Enum):
    CONTINUOUS = "CONTINUOUS"
    DISCRETE = "DISCRETE"
    SEMI_DISCRETE = "SEMI_DISCRETE"
    UNKNOWN = "UNKNOWN"


class HalalStatus(str, Enum):
    VERIFIED_HALAL = "VERIFIED_HALAL"
    NOT_HALAL = "NOT_HALAL"
    UNKNOWN = "UNKNOWN"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class AllergenType(str, Enum):
    GLUTEN_CEREAL = "GLUTEN_CEREAL"
    EGG = "EGG"
    FISH = "FISH"
    CRUSTACEAN = "CRUSTACEAN"
    MOLLUSC = "MOLLUSC"
    PEANUT = "PEANUT"
    SOY = "SOY"
    MILK = "MILK"
    TREE_NUT = "TREE_NUT"
    SULFITE = "SULFITE"


class AllergenRelationshipType(str, Enum):
    CONTAINS = "CONTAINS"
    MAY_CONTAIN = "MAY_CONTAIN"
    SHARED_FACILITY = "SHARED_FACILITY"
    UNKNOWN = "UNKNOWN"


class PrepComplexity(str, Enum):
    NONE = "NONE"
    VERY_SIMPLE = "VERY_SIMPLE"
    SIMPLE = "SIMPLE"
    MODERATE = "MODERATE"
    ADVANCED = "ADVANCED"


class KitchenEquipment(str, Enum):
    STOVE = "STOVE"
    RICE_COOKER = "RICE_COOKER"
    FRIDGE = "FRIDGE"
    MICROWAVE = "MICROWAVE"
    BLENDER = "BLENDER"
    OVEN = "OVEN"
    AIR_FRYER = "AIR_FRYER"
    KNIFE_BOARD = "KNIFE_BOARD"
    NONE = "NONE"


class FoodPlannerEligibilityStatus(str, Enum):
    ELIGIBLE = "ELIGIBLE"
    PARTIAL_DATA = "PARTIAL_DATA"
    ALLERGEN_UNCERTAIN = "ALLERGEN_UNCERTAIN"
    NUTRIENT_DATA_INSUFFICIENT = "NUTRIENT_DATA_INSUFFICIENT"
    DEPRECATED = "DEPRECATED"
