from enum import Enum


class AdaptationDecision(str, Enum):
    CONTINUE_CURRENT_PLAN = "CONTINUE_CURRENT_PLAN"
    HOLD_CURRENT_PLAN = "HOLD_CURRENT_PLAN"
    RECOVERY_RECOMMENDED = "RECOVERY_RECOMMENDED"
    CONSIDER_ADJUSTMENT = "CONSIDER_ADJUSTMENT"
    NEEDS_MORE_DATA = "NEEDS_MORE_DATA"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"


class AdjustmentReviewDomain(str, Enum):
    NONE = "NONE"
    ENERGY_TARGET_REVIEW = "ENERGY_TARGET_REVIEW"
    MEAL_STRUCTURE_REVIEW = "MEAL_STRUCTURE_REVIEW"
    FOOD_CANDIDATE_REVIEW = "FOOD_CANDIDATE_REVIEW"
    BUDGET_REVIEW = "BUDGET_REVIEW"
    SCHEDULE_REVIEW = "SCHEDULE_REVIEW"
    DATA_COLLECTION_REVIEW = "DATA_COLLECTION_REVIEW"


class DataSufficiencyStatus(str, Enum):
    SUFFICIENT = "SUFFICIENT"
    PARTIAL = "PARTIAL"
    INSUFFICIENT = "INSUFFICIENT"


class WeightTrendDirection(str, Enum):
    INCREASING = "INCREASING"
    STABLE = "STABLE"
    DECREASING = "DECREASING"
    INDETERMINATE = "INDETERMINATE"


class AdherenceContextCategory(str, Enum):
    HIGH_CONFIDENCE_ADHERENCE = "HIGH_CONFIDENCE_ADHERENCE"
    MIXED_ADHERENCE = "MIXED_ADHERENCE"
    LOW_ADHERENCE = "LOW_ADHERENCE"
    INSUFFICIENT_REPORTING = "INSUFFICIENT_REPORTING"


class EvaluationConfidence(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    UNKNOWN = "UNKNOWN"


class DayEvidenceQuality(str, Enum):
    USABLE = "USABLE"
    PARTIAL = "PARTIAL"
    UNUSABLE = "UNUSABLE"


class EvaluationReasonCode(str, Enum):
    INSUFFICIENT_EVALUATION_WINDOW = "INSUFFICIENT_EVALUATION_WINDOW"
    INSUFFICIENT_REPORTING = "INSUFFICIENT_REPORTING"
    INSUFFICIENT_WEIGHT_DATA = "INSUFFICIENT_WEIGHT_DATA"
    WEIGHT_TREND_INDETERMINATE = "WEIGHT_TREND_INDETERMINATE"
    WEIGHT_TREND_STABLE = "WEIGHT_TREND_STABLE"
    WEIGHT_TREND_EXPECTED_DIRECTION = "WEIGHT_TREND_EXPECTED_DIRECTION"
    WEIGHT_TREND_OPPOSITE_DIRECTION = "WEIGHT_TREND_OPPOSITE_DIRECTION"
    HIGH_ADHERENCE = "HIGH_ADHERENCE"
    MIXED_ADHERENCE = "MIXED_ADHERENCE"
    LOW_ADHERENCE = "LOW_ADHERENCE"
    BUDGET_FRICTION_PATTERN = "BUDGET_FRICTION_PATTERN"
    SCHEDULE_FRICTION_PATTERN = "SCHEDULE_FRICTION_PATTERN"
    FOOD_AVAILABILITY_PATTERN = "FOOD_AVAILABILITY_PATTERN"
    PREPARATION_FRICTION_PATTERN = "PREPARATION_FRICTION_PATTERN"
    TEMPORARY_DISRUPTION = "TEMPORARY_DISRUPTION"
    ADAPTATION_COOLDOWN_ACTIVE = "ADAPTATION_COOLDOWN_ACTIVE"
    EARLY_TRANSITION_PHASE = "EARLY_TRANSITION_PHASE"
    SAFETY_OUT_OF_SCOPE = "SAFETY_OUT_OF_SCOPE"


class AdaptationEvaluationPolicy:
    VERSION = "NUTRITION_ADAPTATION_EVALUATION_V01"
    MIN_EVALUATION_DAYS = 7
    PREFERRED_EVALUATION_DAYS = 14
    MAX_EVALUATION_DAYS = 28
    MIN_WEIGHT_MEASUREMENTS = 3
    MIN_USABLE_ADHERENCE_DAYS = 5
    MIN_DAYS_BETWEEN_ADAPTATION_REVIEWS = 7
    WEIGHT_STABLE_DAILY_SLOPE_THRESHOLD_KG = 0.02
