from enum import Enum


class FoodPlannerRole(str, Enum):
    STAPLE = "STAPLE"
    PROTEIN_SOURCE = "PROTEIN_SOURCE"
    VEGETABLE = "VEGETABLE"
    FRUIT = "FRUIT"
    ENERGY_ADDON = "ENERGY_ADDON"
    SNACK_ITEM = "SNACK_ITEM"
    BEVERAGE = "BEVERAGE"
    OTHER = "OTHER"


class CandidateMatchStatus(str, Enum):
    STRICT_MATCH = "STRICT_MATCH"
    NEAR_MATCH = "NEAR_MATCH"
    INELIGIBLE = "INELIGIBLE"


class CandidateGenerationStatus(str, Enum):
    CANDIDATES_FOUND = "CANDIDATES_FOUND"
    NO_STRICT_MATCH = "NO_STRICT_MATCH"
    NO_ELIGIBLE_FOODS = "NO_ELIGIBLE_FOODS"
    NEEDS_MORE_DATA = "NEEDS_MORE_DATA"


class CandidateRejectionReason(str, Enum):
    ENERGY_TOO_LOW = "ENERGY_TOO_LOW"
    ENERGY_TOO_HIGH = "ENERGY_TOO_HIGH"
    ALLERGEN_CONFLICT = "ALLERGEN_CONFLICT"
    ALLERGEN_UNKNOWN = "ALLERGEN_UNKNOWN"
    RESTRICTION_CONFLICT = "RESTRICTION_CONFLICT"
    PREPARATION_INCOMPATIBLE = "PREPARATION_INCOMPATIBLE"
    NUTRIENT_DATA_INCOMPLETE = "NUTRIENT_DATA_INCOMPLETE"
    SERVING_UNAVAILABLE = "SERVING_UNAVAILABLE"
    QUALITY_NOT_ELIGIBLE = "QUALITY_NOT_ELIGIBLE"


class CandidatePolicy:
    """
    Centralized Chronos Candidate Generation Policy Parameters (FOOD_CANDIDATE_TEMPLATE_V01).
    """
    VERSION: str = "FOOD_CANDIDATE_P1_2"
    MAX_POOL_PER_ROLE: int = 20
    MAX_SERVING_OPTIONS_PER_FOOD: int = 4
    MAX_COMBINATION_SIZE: int = 4
    MAX_CANDIDATES_RETURNED: int = 20
    DEFAULT_SERVING_MULTIPLIERS = (0.5, 1.0, 1.5, 2.0)
