from enum import Enum


class FoodPlannerRole(str, Enum):
    STAPLE = "STAPLE"
    PROTEIN_SOURCE = "PROTEIN_SOURCE"
    VEGETABLE = "VEGETABLE"
    FRUIT = "FRUIT"
    ENERGY_ADDON = "ENERGY_ADDON"
    SNACK_ITEM = "SNACK_ITEM"
    BEVERAGE = "BEVERAGE"
    OTHER = "OTHER"


class CandidateMatchStatus(str, Enum):
    STRICT_MATCH = "STRICT_MATCH"
    NEAR_MATCH = "NEAR_MATCH"
    INELIGIBLE = "INELIGIBLE"


class CandidateGenerationStatus(str, Enum):
    CANDIDATES_FOUND = "CANDIDATES_FOUND"
    NO_STRICT_MATCH = "NO_STRICT_MATCH"
    NO_ELIGIBLE_FOODS = "NO_ELIGIBLE_FOODS"
    NEEDS_MORE_DATA = "NEEDS_MORE_DATA"
    NOT_ELIGIBLE = "NOT_ELIGIBLE"


class CandidateRejectionReason(str, Enum):
    ALLERGEN_CONFLICT = "ALLERGEN_CONFLICT"
    ALLERGEN_UNKNOWN = "ALLERGEN_UNKNOWN"
    RESTRICTION_CONFLICT = "RESTRICTION_CONFLICT"
    HALAL_STATUS_UNVERIFIED = "HALAL_STATUS_UNVERIFIED"
    HALAL_RESTRICTION_CONFLICT = "HALAL_RESTRICTION_CONFLICT"
    PREPARATION_INCOMPATIBLE = "PREPARATION_INCOMPATIBLE"
    EQUIPMENT_UNKNOWN = "EQUIPMENT_UNKNOWN"
    NUTRIENT_DATA_INCOMPLETE = "NUTRIENT_DATA_INCOMPLETE"
    QUALITY_NOT_ELIGIBLE = "QUALITY_NOT_ELIGIBLE"
    ENERGY_TOO_LOW = "ENERGY_TOO_LOW"
    ENERGY_TOO_HIGH = "ENERGY_TOO_HIGH"
    NUTRITION_NOT_ELIGIBLE = "NUTRITION_NOT_ELIGIBLE"


class CandidatePolicy:
    """
    Centralized Chronos Candidate Generation & Ranking Policy Parameters.
    """
    VERSION: str = "FOOD_CANDIDATE_P1_2"
    RANKING_POLICY_VERSION: str = "FOOD_CANDIDATE_RANKING_V01"
    MAX_POOL_PER_ROLE: int = 20
    MAX_SERVING_OPTIONS_PER_FOOD: int = 4
    MAX_COMBINATION_SIZE: int = 4
    MAX_CANDIDATES_RETURNED: int = 20
    NEAR_MATCH_EXTENSION_RATIO: float = 0.10  # 10% extension beyond slot bounds
    DEFAULT_CONTINUOUS_MULTIPLIERS = (0.5, 1.0, 1.5, 2.0)
    DEFAULT_DISCRETE_MULTIPLIERS = (1.0, 2.0, 3.0)
