from enum import Enum


class ApplicationStatus(str, Enum):
    APPLIED = "APPLIED"
    ALREADY_APPLIED = "ALREADY_APPLIED"
    PROPOSAL_NOT_ACCEPTED = "PROPOSAL_NOT_ACCEPTED"
    PROPOSAL_EXPIRED = "PROPOSAL_EXPIRED"
    PROPOSAL_STALE = "PROPOSAL_STALE"
    ELIGIBILITY_CHANGED = "ELIGIBILITY_CHANGED"
    EVIDENCE_CHANGED = "EVIDENCE_CHANGED"
    TARGET_CONFLICT = "TARGET_CONFLICT"
    REVISION_CONFLICT = "REVISION_CONFLICT"
    ADAPTIVE_LIMIT_REACHED = "ADAPTIVE_LIMIT_REACHED"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    UNSUPPORTED_POLICY_VERSION = "UNSUPPORTED_POLICY_VERSION"
    ROLLBACK_OCCURRED = "ROLLBACK_OCCURRED"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"


class StateRevisionSourceType(str, Enum):
    INITIAL_BASELINE = "INITIAL_BASELINE"
    USER_CONFIRMED_ADJUSTMENT = "USER_CONFIRMED_ADJUSTMENT"
    MANUAL_OVERRIDE = "MANUAL_OVERRIDE"


class DownstreamArtifactType(str, Enum):
    MEAL_STRUCTURE = "MEAL_STRUCTURE"
    FOOD_CANDIDATES = "FOOD_CANDIDATES"
    BUDGET_SELECTION = "BUDGET_SELECTION"
    DAILY_NUTRITION_PLAN = "DAILY_NUTRITION_PLAN"


class ApplicationReasonCode(str, Enum):
    USER_CONFIRMED_ENERGY_INCREASE = "USER_CONFIRMED_ENERGY_INCREASE"
    IDEMPOTENT_REPLAY = "IDEMPOTENT_REPLAY"
    PROPOSAL_NOT_ACCEPTED = "PROPOSAL_NOT_ACCEPTED"
    PROPOSAL_EXPIRED = "PROPOSAL_EXPIRED"
    PROPOSAL_STALE = "PROPOSAL_STALE"
    ELIGIBILITY_CHANGED = "ELIGIBILITY_CHANGED"
    EVIDENCE_CHANGED = "EVIDENCE_CHANGED"
    TARGET_CONFLICT = "TARGET_CONFLICT"
    REVISION_CONFLICT = "REVISION_CONFLICT"
    ADAPTIVE_LIMIT_REACHED = "ADAPTIVE_LIMIT_REACHED"
    IDEMPOTENCY_KEY_MISMATCH = "IDEMPOTENCY_KEY_MISMATCH"
    ARITHMETIC_CORRUPTION = "ARITHMETIC_CORRUPTION"
    UNSUPPORTED_POLICY_VERSION = "UNSUPPORTED_POLICY_VERSION"


class ApplicationPolicy:
    VERSION = "NUTRITION_ADJUSTMENT_APPLICATION_P1_9"
    REVISION_POLICY = "NUTRITION_STATE_REVISION_V01"
    INVALIDATION_POLICY = "NUTRITION_DOWNSTREAM_INVALIDATION_V01"
    IDEMPOTENCY_POLICY = "NUTRITION_ADJUSTMENT_IDEMPOTENCY_V01"

    MAX_SINGLE_ENERGY_ADJUSTMENT_KCAL: int = 100
    MAX_CUMULATIVE_ADAPTIVE_ADJUSTMENT_KCAL: int = 400
    SUPPORTED_GOAL: str = "NUTRITION_WEIGHT_GAIN"
    SUPPORTED_DOMAIN: str = "ENERGY_TARGET"
