from enum import Enum


class MealCheckinStatus(str, Enum):
    ATE_AS_PLANNED = "ATE_AS_PLANNED"
    ATE_PARTIALLY = "ATE_PARTIALLY"
    ATE_DIFFERENT_FOOD = "ATE_DIFFERENT_FOOD"
    SKIPPED = "SKIPPED"
    NOT_REPORTED = "NOT_REPORTED"


class MealCompletionState(str, Enum):
    FULL = "FULL"
    PARTIAL = "PARTIAL"
    SKIPPED = "SKIPPED"
    NOT_REPORTED = "NOT_REPORTED"


class TimingAdherenceStatus(str, Enum):
    WITHIN_WINDOW = "WITHIN_WINDOW"
    OUTSIDE_WINDOW = "OUTSIDE_WINDOW"
    UNKNOWN = "UNKNOWN"


class FoodChoiceAdherence(str, Enum):
    AS_PLANNED = "AS_PLANNED"
    PARTIAL_MATCH = "PARTIAL_MATCH"
    DIFFERENT = "DIFFERENT"
    SKIPPED = "SKIPPED"
    NOT_REPORTED = "NOT_REPORTED"


class EnergyAdherenceStatus(str, Enum):
    WITHIN_PLANNED_RANGE = "WITHIN_PLANNED_RANGE"
    BELOW_PLANNED_RANGE = "BELOW_PLANNED_RANGE"
    ABOVE_PLANNED_RANGE = "ABOVE_PLANNED_RANGE"
    UNKNOWN = "UNKNOWN"


class ReportingCompleteness(str, Enum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    NONE = "NONE"


class ActualIntakeCertainty(str, Enum):
    EXACT = "EXACT"
    APPROXIMATE = "APPROXIMATE"
    UNKNOWN = "UNKNOWN"


class ActualFoodSourceType(str, Enum):
    PLANNED_ITEM = "PLANNED_ITEM"
    FOOD_KNOWLEDGE_MATCH = "FOOD_KNOWLEDGE_MATCH"
    USER_REPORTED_UNRESOLVED = "USER_REPORTED_UNRESOLVED"


class DeviationReason(str, Enum):
    NOT_HUNGRY = "NOT_HUNGRY"
    NO_TIME = "NO_TIME"
    FOOD_UNAVAILABLE = "FOOD_UNAVAILABLE"
    TOO_EXPENSIVE = "TOO_EXPENSIVE"
    SCHEDULE_CHANGED = "SCHEDULE_CHANGED"
    SOCIAL_EVENT = "SOCIAL_EVENT"
    ATE_OUTSIDE = "ATE_OUTSIDE"
    PREPARATION_DIFFICULT = "PREPARATION_DIFFICULT"
    FORGOT = "FORGOT"
    OTHER = "OTHER"
    PREFER_NOT_TO_SAY = "PREFER_NOT_TO_SAY"


class AdherencePolicy:
    VERSION = "DAILY_NUTRITION_CHECKIN_P1_6"
    ADHERENCE_POLICY_VERSION = "NUTRITION_ADHERENCE_V01"
