from enum import Enum


class DailyPlanStatus(str, Enum):
    READY = "READY"
    READY_WITH_WARNINGS = "READY_WITH_WARNINGS"
    NEEDS_MORE_DATA = "NEEDS_MORE_DATA"
    NOT_ELIGIBLE = "NOT_ELIGIBLE"
    INFEASIBLE = "INFEASIBLE"
    SEARCH_INCOMPLETE = "SEARCH_INCOMPLETE"


class DailyPlanWarningSeverity(str, Enum):
    INFO = "INFO"
    CAUTION = "CAUTION"
    BLOCKING = "BLOCKING"


class DailyPlanWarningCode(str, Enum):
    LOW_CONFIDENCE_PRICE = "LOW_CONFIDENCE_PRICE"
    STALE_PRICE_USED = "STALE_PRICE_USED"
    NUTRITION_NEAR_MATCH = "NUTRITION_NEAR_MATCH"
    SEARCH_SPACE_TRUNCATED = "SEARCH_SPACE_TRUNCATED"
    PARTIAL_MACRO_DATA = "PARTIAL_MACRO_DATA"


class MacroCompleteness(str, Enum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"


class DailyPlanPolicy:
    VERSION = "DAILY_NUTRITION_PLAN_ASSEMBLY_P1_5"
    ASSEMBLY_POLICY_VERSION = "PLAN_ASSEMBLY_V01"
