from enum import Enum


class BudgetPeriod(str, Enum):
    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"
    CUSTOM_PERIOD = "CUSTOM_PERIOD"


class BudgetSource(str, Enum):
    USER_DECLARED = "USER_DECLARED"
    USER_UPDATED = "USER_UPDATED"
    DERIVED_FROM_PERIOD = "DERIVED_FROM_PERIOD"


class CandidateBudgetStatus(str, Enum):
    WITHIN_BUDGET = "WITHIN_BUDGET"
    OVER_BUDGET = "OVER_BUDGET"
    UNKNOWN_COST = "UNKNOWN_COST"
    LOW_CONFIDENCE_COST = "LOW_CONFIDENCE_COST"


class BudgetSelectionStatus(str, Enum):
    SELECTION_FOUND = "SELECTION_FOUND"
    SELECTION_FOUND_WITH_LOW_CONFIDENCE_PRICE = "SELECTION_FOUND_WITH_LOW_CONFIDENCE_PRICE"
    NO_BUDGET_FEASIBLE_SELECTION = "NO_BUDGET_FEASIBLE_SELECTION"
    NEEDS_MORE_PRICE_DATA = "NEEDS_MORE_PRICE_DATA"
    BUDGET_NOT_CONFIGURED = "BUDGET_NOT_CONFIGURED"
    NEEDS_MORE_BUDGET_DATA = "NEEDS_MORE_BUDGET_DATA"
    BUDGET_ALREADY_EXCEEDED = "BUDGET_ALREADY_EXCEEDED"
    NO_ELIGIBLE_CANDIDATES = "NO_ELIGIBLE_CANDIDATES"


class BudgetSelectionPolicy:
    """
    Centralized Chronos Budget-Aware Selection Policy Parameters.
    """
    VERSION: str = "BUDGET_SELECTION_P1_4"
    ALLOCATION_POLICY_VERSION: str = "BUDGET_ALLOCATION_V01"
    SEARCH_POLICY_VERSION: str = "BUDGET_SELECTION_SEARCH_V01"
    RANKING_POLICY_VERSION: str = "BUDGET_SELECTION_RANKING_V01"

    MAX_CANDIDATES_PER_SLOT_FOR_BUDGET_SEARCH: int = 15
    MAX_DAILY_COMBINATIONS_EVALUATED: int = 5000
    MAX_SELECTION_RESULTS_RETURNED: int = 5
    DEFAULT_CURRENCY: str = "IDR"
